export enum EmitterEvents {
    CONFIDENCE_CHANGE = "CONFIDENCE_CHANGE",
    PAGE_TIMEOUT = "PAGE_TIMEOUT",
    PAGE_FETCH = "PAGE_FETCH",
    STOP_TIMER = "STOP_TIMER",
    START_TIMER = "START_TIMER",
    GROUP_FORMED = "GROUP_FORMED"
}
