const uuid = require("./uuid");

module.exports = () => {
    return Object.assign({}, {
        context_id
            :
            "ENGG1200N_6660_00001",
        context_label
            :
            "ENGG1200N_6660_00001",
        context_title
            :
            "Staging TEST - [ENGG1200] Semester 2, 2015",
        context_type
            :
            "CourseSection",
        ext_lms
            :
            "learn-9.1.201510",
        launch_presentation_document_target
            :
            "frame",
        launch_presentation_locale
            :
            "en_US",
        launch_presentation_return_url
            :
            "https://staging-blackboard.elearning.uq.edu.au/webapps/osc-BasicLTI-BBLEARN/return.jsp?id=moocchat&course_id=_22551_1&content_id=_160288_1&lti_page=tool&globalNavigation=false",
        lis_course_offering_sourcedid
            :
            "ENGG1200N_6660_00001",
        lis_course_section_sourcedid
            :
            "ENGG1200N_6660_00001",
        lis_person_contact_email_primary
            :
            "james.li1@uq.edu.au",
        lis_person_name_family
            :
            "Li",
        lis_person_name_full
            :
            "James Li",
        lis_person_name_given
            :
            "James",
        lis_person_sourcedid
            :
            "806243",
        lti_message_type
            :
            "basic-lti-launch-request",
        lti_version
            :
            "LTI-1p0",
        oauth_callback
            :
            "about:blank",
        oauth_consumer_key
            :
            "moocchat.uqcloud.net",
        oauth_nonce
            :
            "3373154933196515",
        oauth_signature
            :
            "+AKF4oayRUKaIjCL80z6u5+yAms=",
        oauth_signature_method
            :
            "HMAC-SHA1",
        oauth_timestamp
            :
            "1466998028",
        oauth_version
            :
            "1.0",
        resource_link_id
            :
            "ENGG1200N_6660_00001_160288_1",
        resource_link_title
            :
            "MOOCchat",
        roles
            :
            "TeachingAssistant",
        tool_consumer_info_product_family_code
            :
            "learn",
        tool_consumer_info_version
            :
            "9.1.201510",
        tool_consumer_instance_contact_email
            :
            "bbadmin@elearning.uq.edu.au",
        tool_consumer_instance_description
            :
            "The University of Queensland",
        tool_consumer_instance_guid
            :
            "a757a9cdd8d4485796c994b66de079b7",
        tool_consumer_instance_name
            :
            "UQ",
        tool_consumer_instance_url
            :
            "https://staging-blackboard.elearning.uq.edu.au",
        user_id
            :
            uuid() + "uqjli23"
    });
}